version: "3.9"

services:
  app:
    build: .
    container_name: mg-fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"